name: Qodana
on:
  workflow_dispatch:

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
    steps:
      - uses: docker/login-action@v3
        with:
          registry: registry.jetbrains.team
          username: ${{ secrets.SPACE_USERNAME }}
          password: ${{ secrets.SPACE_PASSWORD }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        with:
          args: --property=idea.kotlin.plugin.use.k2=true,--property=idea.is.internal=true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_K2_MASTER }} # read the steps about it below
